gcp_login:
  project_id : loan-pred-vertex
  region : asia-south1
  zone : asia-south1-a

bigquery:


gcs:
  bucket_name : loan_pred_e2e
  gcs_raw_file_path : data/raw_data/loan_approval_dataset.csv
  gcs_processed_file_path : data/processed_data
